/*
MACOS_HOST.H

Internals of the macOS port's host: the native arm64 program that runs the
game's ILP32 guest (docs/macos-port-audit.md, tools/macos_guest_build.py).
The contract with the guest is the Android port's,
port/android/include/halo_android_abi.h, with one difference: the guest's
32-bit addresses are offsets into a 4 GB arena aligned to 4 GB, so a guest
address g is the host address host_arena | g, and the low 32 bits of a host
address inside the arena are its guest address.

The host's functions take native pointers. The bridges between the guest's
imports and these functions (generated by tools/macos_host_bridges.py)
translate the guest's pointer arguments into the arena.
*/

#ifndef __HALO_MACOS_HOST_H
#define __HALO_MACOS_HOST_H

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>

#include "halo_android_abi.h"

/* ---------- the arena (host_memory.c) */

extern uintptr_t host_arena;

static inline void *host_pointer(uint64_t guest)
{
	return guest ? (void *)(host_arena | (uint32_t)guest) : NULL;
}

static inline uint32_t guest_pointer(const void *native)
{
	return (uint32_t)(uintptr_t)native;
}

/* ---------- logging and termination (host_main.c) */

#define HOST_LOG_INFO 4
#define HOST_LOG_WARN 5
#define HOST_LOG_ERROR 6
void host_logf(int priority, const char *format, ...) __attribute__((format(printf, 2, 3)));
/* logs, shows the message to the player and terminates */
void host_fatal(const char *format, ...) __attribute__((format(printf, 1, 2), noreturn));
void host_exit(int code) __attribute__((noreturn));
int host_errno(void);
/* the guest's errno value (Linux's numbering) for a Darwin errno */
int host_linux_errno(int native_errno);
/* the user's folder: ~/Library/Application Support/Halo CE */
const char *host_user_root(void);

/* ---------- guest memory (host_memory.c)

The host reserves the whole arena at start-up and hands out its pages: the
Xbox window and the image at their fixed guest addresses, and everything else
(the guest's malloc arenas, thread stacks, anonymous mappings) from free
ranges, at the 16 KB page size of Apple Silicon. */

/* reserves the arena and the fixed ranges; 0 on success */
int host_memory_initialize(uint32_t image_base, uint32_t image_end);
/* page-granular allocations in the arena; NULL on failure */
void *host_low_map(size_t size, int protection);
void host_low_unmap(void *address, size_t size);
/* 1 if the native range lies inside the arena */
int host_low_owns(uintptr_t address, size_t size);
/* the guest's mmap, munmap and mprotect (Linux's flags; host_syscall.c) */
long host_guest_mmap(uint64_t address, uint64_t size, int protection, int flags, int fd, int64_t offset);
long host_guest_munmap(uint64_t address, uint64_t size);
long host_guest_mprotect(uint64_t address, uint64_t size, int protection);
void host_install_signal_handlers(void);

/* ---------- the guest image (host_loader.c) */

struct host_guest_image
{
	const struct halo_guest_header *header;
	uint32_t base, end;
};

extern struct host_guest_image host_image;

/* aliases the guest code signed into this executable into the arena,
copies its data and fills its import table; 0 on success */
int host_load_image(void);
/* the bridge of the named import, or NULL (generated) */
void *host_resolve_import(const char *name);

/* ---------- entering guest code (host_thread.c, guest_call.S) */

uint32_t host_guest_invoke(uintptr_t function, uint32_t a, uint32_t b, uint32_t c, uint32_t d, uintptr_t arena);
uint64_t host_guest_on_stack(uintptr_t function, uint32_t argument, uintptr_t arena, void *stack_top);
/* calls the guest function at guest address function with up to four 32-bit
arguments, on this thread, whose stack must be in the arena (giving the
thread a guest struct pthread first if it has none); returns the guest's w0 */
uint32_t host_call_guest(uint32_t function, uint32_t a, uint32_t b, uint32_t c, uint32_t d);
/* starts a thread running function(argument) with its stack in the arena;
0 or an errno value */
int host_native_thread_create(void *(*function)(void *), void *argument, size_t stack_size);
/* runs the guest's __guest_start(boot) on the calling thread (the main
thread, which SDL needs for windows and events), on a stack in the arena;
does not return */
void host_run_guest_main(uint32_t boot) __attribute__((noreturn));
void host_debug_thread_started(void);
void host_debug_thread_exited(void);

/* ---------- OpenGL (host_gl.c) */

/* the attributes of the context the host makes, whatever the guest asked
for: OpenGL 4.1 core, on which the guest's OpenGL ES 3 renderer runs */
void host_gl_prepare_context(void);
/* after the context is made current */
void host_gl_context_created(void);

#endif
