#!/usr/bin/env python3
"""Embed the macOS guest image in the host executable.

Apple Silicon only executes signed code pages, so the guest's code cannot be
loaded from a file at run time. This splits the linked guest ELF
(port/macos/guest.ld) into its two load segments and writes:

- guest_image.S: the code in a __TEXT section of the host, covered by the
  app's code signature, which the host aliases read/execute into the arena
  with vm_remap (port/macos/host/host_loader.c); and the initial data in
  __DATA_CONST, which the host copies into writable arena pages;
- guest_image.h: the layout constants for the host.

The approach comes from the iOS port by Nicholas Dominici
(github.com/NicholasDominici/halo-ce-ios, tools/ios_embed_guest.py, CC0 1.0).

Usage: macos_embed_guest.py guest.elf output_directory
"""

import struct
import sys
from pathlib import Path

IMAGE_BASE = 0x88000000
PAGE = 0x4000
EM_AARCH64 = 183
PT_LOAD = 1
PF_RX = 5
PF_RW = 6


def load_segments(data: bytes):
    if data[:6] != b"\x7fELF\x02\x01" or struct.unpack_from("<H", data, 18)[0] != EM_AARCH64:
        raise SystemExit("expected a little-endian AArch64 ELF64 guest image")
    program_headers = struct.unpack_from("<Q", data, 32)[0]
    entry_size, count = struct.unpack_from("<HH", data, 54)
    segments = []
    for index in range(count):
        kind, flags, offset, address, _, file_size, memory_size, _ = struct.unpack_from(
            "<IIQQQQQQ", data, program_headers + index * entry_size)
        if kind != PT_LOAD:
            continue
        if offset + file_size > len(data) or file_size > memory_size or address + memory_size > 1 << 32:
            raise SystemExit("guest segment outside the file or the 32-bit address space")
        segments.append((flags, address, file_size, memory_size, data[offset:offset + file_size]))
    return segments


def embed(elf: Path, destination: Path) -> None:
    segments = load_segments(elf.read_bytes())
    if [segment[0] for segment in segments] != [PF_RX, PF_RW]:
        raise SystemExit("the guest must have exactly one RX and then one RW load segment")
    code, writable = segments
    if code[1] != IMAGE_BASE or writable[1] % PAGE or code[1] + code[3] > writable[1]:
        raise SystemExit("unexpected guest layout: code must start at 0x88000000 and data on a 16 KB page")
    code_bytes = code[4].ljust(writable[1] - code[1], b"\0")
    image_end = (writable[1] + writable[3] + PAGE - 1) & ~(PAGE - 1)
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "guest-code.bin").write_bytes(code_bytes)
    (destination / "guest-data.bin").write_bytes(writable[4])
    (destination / "guest_image.h").write_text(
        "/* generated by tools/macos_embed_guest.py; do not edit */\n"
        "#ifndef __HALO_MACOS_GUEST_IMAGE_H\n#define __HALO_MACOS_GUEST_IMAGE_H\n"
        f"#define MACOS_GUEST_CODE_SIZE 0x{len(code_bytes):x}u\n"
        f"#define MACOS_GUEST_DATA_ADDRESS 0x{writable[1]:x}u\n"
        f"#define MACOS_GUEST_DATA_SIZE 0x{writable[2]:x}u\n"
        f"#define MACOS_GUEST_IMAGE_END 0x{image_end:x}u\n"
        "extern const unsigned char halo_guest_code[], halo_guest_data[];\n"
        "#endif\n")
    # .incbin takes the path as the assembler is run; ninja runs from the
    # repository root, so the paths are relative to it
    (destination / "guest_image.S").write_text(
        "/* generated by tools/macos_embed_guest.py; the guest code is signed with the app */\n"
        "\t.section __TEXT,__halo_guest,regular,pure_instructions\n"
        "\t.p2align 14\n"
        "\t.globl _halo_guest_code\n"
        "_halo_guest_code:\n"
        f"\t.incbin \"{(destination / 'guest-code.bin').as_posix()}\"\n"
        "\t.p2align 14\n"
        "\t.section __DATA_CONST,__halo_data\n"
        "\t.p2align 3\n"
        "\t.globl _halo_guest_data\n"
        "_halo_guest_data:\n"
        f"\t.incbin \"{(destination / 'guest-data.bin').as_posix()}\"\n")


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    embed(Path(sys.argv[1]), Path(sys.argv[2]))


if __name__ == "__main__":
    main()
