#!/usr/bin/env python3
"""Turn the __text section of an arm64_32 Mach-O object into a C header.

The macOS hypervisor probe (``ninja macos_hvf_probe``) copies ILP32 guest code
into the memory of a Hypervisor.framework VM.  The probe has no loader, so the
object must have no relocations.  The header holds the bytes and the offset of
each external function in the section.

Usage: macos_guest_blob.py <object.o> <output.h> <array name>
"""

import struct
import sys
from pathlib import Path

MH_MAGIC = 0xFEEDFACE
CPU_TYPE_ARM64_32 = 0x0200000C
LC_SEGMENT = 0x1
LC_SYMTAB = 0x2
N_EXT = 0x01
N_TYPE = 0x0E
N_SECT = 0x0E


def extract(data: bytes):
    magic, cputype, _, _, ncmds, _, _ = struct.unpack_from("<7I", data, 0)
    if magic != MH_MAGIC or cputype != CPU_TYPE_ARM64_32:
        raise SystemExit("expected a 32-bit Mach-O object for arm64_32")
    offset = 28
    text = None
    text_index = None
    section_index = 0
    symtab = None
    for _ in range(ncmds):
        cmd, cmdsize = struct.unpack_from("<2I", data, offset)
        if cmd == LC_SEGMENT:
            nsects = struct.unpack_from("<I", data, offset + 48)[0]
            for s in range(nsects):
                base = offset + 56 + s * 68
                sectname = data[base:base + 16].rstrip(b"\0").decode()
                segname = data[base + 16:base + 32].rstrip(b"\0").decode()
                addr, size, fileoff, _, _, nreloc = struct.unpack_from("<6I", data, base + 32)
                section_index += 1
                if (segname, sectname) == ("__TEXT", "__text"):
                    if nreloc:
                        raise SystemExit(f"__text has {nreloc} relocations; the probe has no loader")
                    text = (addr, data[fileoff:fileoff + size])
                    text_index = section_index
                elif size and segname != "__LD":
                    raise SystemExit(f"unexpected non-empty section {segname},{sectname}")
        elif cmd == LC_SYMTAB:
            symtab = struct.unpack_from("<4I", data, offset + 8)
        offset += cmdsize
    if text is None or symtab is None:
        raise SystemExit("object has no __text section or no symbol table")
    symoff, nsyms, stroff, _ = symtab
    symbols = []
    for i in range(nsyms):
        strx, ntype, nsect, _, value = struct.unpack_from("<IBBHI", data, symoff + i * 12)
        if ntype & N_EXT and ntype & N_TYPE == N_SECT and nsect == text_index:
            end = data.index(b"\0", stroff + strx)
            name = data[stroff + strx:end].decode().lstrip("_")
            symbols.append((name, value - text[0]))
    return text[1], sorted(symbols, key=lambda item: item[1])


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    obj, out, array = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    code, symbols = extract(obj.read_bytes())
    lines = [f"/* generated by tools/macos_guest_blob.py from {obj.as_posix()} */", ""]
    lines += [f"#define {array.upper()}_{name.upper()} 0x{value:x}u" for name, value in symbols]
    lines += ["", f"static const unsigned char {array}[] = {{"]
    for i in range(0, len(code), 12):
        lines.append("\t" + ", ".join(f"0x{b:02x}" for b in code[i:i + 12]) + ",")
    lines += ["};", ""]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
